### ISSUE TITLE
Behaviour for mapping is weird

### ISSUE THREAD

**Issue by zhengye1** [dataclass-mapper/dataclass-mapper#20] opened 2023-09-12 20:34 UTC
When I run the code I got 
```
account_billing=AccountBillingEdm(id='1234') billing_group=BillingGroupEdm(id='1223')
account=AccountBiller(id=None, status_id=None) billing_group={'id': <Spezial.IGNORE_MISSING_MAPPING: 2>}  
C:\Users\zhibo\eip\venv\Lib\site-packages\pydantic\main.py:353: UserWarning: Pydantic serializer warnings:
  Expected `BillingGroupBiller` but got `dict` - serialized value may not be as expected                  
  return self.__pydantic_serializer__.to_json(                                                            
{"account":{"id":null,"status_id":null},"billing_group":{"id":2}}
```

However after the conversion I expected to get `account=AccountBiller(id=None, status_id=None) billing_group={'id': None} `, why the behaviour is {"account":{"id":null,"status_id":null},"billing_group":{"id":2}}

Here is the code I am using to test
```
from enum import Enum
from typing import List

from dataclass_mapper import mapper, mapper_from, map_to, IGNORE_MISSING_MAPPING
from pydantic import BaseModel, Field
from typing import Optional


class AccountStateBiller(str, Enum):
    """
    The account states
    """
    ACTIVE = "0"
    CLOSED = "1"


account_billing_edm_to_biller = {
    "id": IGNORE_MISSING_MAPPING,
    "status_id": IGNORE_MISSING_MAPPING
}


class AccountBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    status_id: Optional[AccountStateBiller] = Field(default=None)


@mapper(AccountBiller, account_billing_edm_to_biller)
class AccountBillingEdm(BaseModel):
    id: str = Field(..., description="The account unique identifier")


@mapper(AccountBillingEdm)
@mapper_from(AccountBillingEdm)
class AccountBillingSfcc(BaseModel):
    id: str = Field(..., description="The account unique identifier")


# BillingGroupEdm -> BillingGroupBiller
billing_group_edm_to_billing_group_biller = lambda self: None if self.billing_group is None else {
    "id": IGNORE_MISSING_MAPPING
}

fact_account_billing_edm_to_biller = {
    "account": "account_billing",
    "billing_group": billing_group_edm_to_billing_group_biller}


class BillingGroupBiller(BaseModel):
    id: Optional[str] = Field(default=None)


class FactAccountBillingBiller(BaseModel):
    account: AccountBiller = Field(...)
    billing_group: Optional[BillingGroupBiller] = Field(default=None)


class BillingGroupEdm(BaseModel):
    id: Optional[str] = Field(default=None)


@mapper(FactAccountBillingBiller, fact_account_billing_edm_to_biller)
class FactAccountEdm(BaseModel):
    account_billing: AccountBillingEdm = Field(...)
    billing_group: Optional[BillingGroupEdm] = Field(default=None)

    @staticmethod
    def get_account() -> List['FactAccountEdm']:
        return FactAccountEdm(account_billing=map_to(AccountBillingSfcc(id="1234"), AccountBillingEdm),
                              billing_group=BillingGroupEdm(id="1223"))


factAccountEdm = FactAccountEdm.get_account()
print(str(factAccountEdm))
result = map_to(factAccountEdm, FactAccountBillingBiller)
print(str(result))
print(result.model_dump_json())

```

**Comment by jakobkogler** [comment] 2023-09-13 11:25
Hello.
The problem is in the mapping definition for the `billing_group`:

```python
billing_group_edm_to_billing_group_biller = lambda self: None if self.billing_group is None else {
    "id": IGNORE_MISSING_MAPPING
}

fact_account_billing_edm_to_biller = {
    "account": "account_billing",
    "billing_group": billing_group_edm_to_billing_group_biller}
```

If you use a lambda function inside a mapping, that lambda is called during the mapping, and the return value is stored the the target class. We don't check the return value, and do some kind of mapping manipulation here.

So in your case, since the variable `factAccountEdm` has the billing group `BillingGroupEdm(id="1223")` assigned to it, the lambda `lambda self: None if self.billing_group is None else { "id": IGNORE_MISSING_MAPPING }` returns the dictionary `{"id": IGNORE_MISSING_MAPPING }` and that is stored inside the resulting object.
The warning that you get comes from Pydantic, as Pydantic doesn't understand the `IGNORE_MISSING_MAPPING` param.

---

If I'm understanding you correctly, you want the following behavior:
- if the `billing_group` is `None`, then also store `None`.
- if the `billing_group` is not `None`, then map the `billing_group` object of type `BillingGroupEdm` to a `BillingGroupBiller` object and ignore the id.

In that case you need to define a mapping between `BillingGroupEdm` and `BillingGroupBiller` in which you ignore the Id, and the rest is automatically handled via the library:
- If the `billing_group` is `None`, then it will also automatically be stored as `None` in the target object (since the target attribute is `Optional[BillingGroupBiller]` and has a default value of `None`).
- And if it's not `None`, then it's recursively mapped to a `BillingGroupBiller`.

```python
class BillingGroupBiller(BaseModel):
    id: Optional[str] = Field(default=None)


class FactAccountBillingBiller(BaseModel):
    account: AccountBiller = Field(...)
    billing_group: Optional[BillingGroupBiller] = Field(default=None)


@mapper(BillingGroupBiller, {"id": IGNORE_MISSING_MAPPING})
class BillingGroupEdm(BaseModel):
    id: Optional[str] = Field(default=None)


@mapper(FactAccountBillingBiller, {"account": "account_billing"})
class FactAccountEdm(BaseModel):
    account_billing: AccountBillingEdm = Field(...)
    billing_group: Optional[BillingGroupEdm] = Field(default=None)
```

**Comment by jakobkogler** [comment] 2023-09-13 11:25
I hope that helped.
 
 And btw, I've deprecated the `IGNORE_MISSING_MAPPING` parameter, as the name was a bit confusing.
 It's now called `init_with_default()`, and does excatly what the name suggests. It initializes that field with the default value of that field (and throw an error if it doesn't have a default).

 ```python
 from dataclass_mapper import init_with_default`
 
 @mapper(BillingGroupBiller, {"id": init_with_default()})
class BillingGroupEdm(BaseModel):
    id: Optional[str] = Field(default=None)
```

**Comment by zhengye1** [comment] 2023-09-13 14:21
I adding one more mapping into the my old and here is the new version
```
from enum import Enum
from typing import List

from dataclass_mapper import mapper, mapper_from, map_to, IGNORE_MISSING_MAPPING, init_with_default
from pydantic import BaseModel, Field
from typing import Optional


class AccountStateBiller(str, Enum):
    """
    The account states
    """
    ACTIVE = "0"
    CLOSED = "1"


class PaymentType(str, Enum):
    prepaid = "Prepaid"
    postpaid = "Postpaid"


class PaymentTypeBiller(str, Enum):
    POST_PAID = "POST_PAID"
    PRE_PAID = "PRE_PAID"


account_billing_edm_to_biller = {
    "id": IGNORE_MISSING_MAPPING,
    "status_id": IGNORE_MISSING_MAPPING
}


class AccountBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    status_id: Optional[AccountStateBiller] = Field(default=None)


@mapper(AccountBiller, account_billing_edm_to_biller)
class AccountBillingEdm(BaseModel):
    id: str = Field(..., description="The account unique identifier")


@mapper(AccountBillingEdm)
@mapper_from(AccountBillingEdm)
class AccountBillingSfcc(BaseModel):
    id: str = Field(..., description="The account unique identifier")


# BillingGroupEdm -> BillingGroupBiller
billing_group_edm_to_billing_group_biller = lambda self: None if self.billing_group is None else {
    "id": IGNORE_MISSING_MAPPING,
    "billing_group_type": PaymentTypeBiller.POST_PAID if self.billing_group.billing_group_type == PaymentType.postpaid else PaymentTypeBiller.PRE_PAID
}

fact_account_billing_edm_to_biller = {
    "account": "account_billing",
    "billing_group": billing_group_edm_to_billing_group_biller
}


class BillingGroupBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    billing_group_type: PaymentTypeBiller = Field(...)


class FactAccountBillingBiller(BaseModel):
    account: AccountBiller = Field(...)
    billing_group: Optional[BillingGroupBiller] = Field(default=None,
                                                        description="Attributes relevant to a billing group needed to "
                                                                    "be stored in CD Rator")


class BillingGroupEdm(BaseModel):
    id: Optional[str] = Field(default=None)
    billing_group_type: PaymentType = Field(...)


@mapper(FactAccountBillingBiller, fact_account_billing_edm_to_biller)
class AccountEdm(BaseModel):
    account_billing: AccountBillingEdm = Field(...)
    billing_group: Optional[BillingGroupEdm] = Field(default=None)

    @staticmethod
    def get_account() -> 'AccountEdm':
        return AccountEdm(account_billing=map_to(AccountBillingSfcc(id="1234"), AccountBillingEdm),
                          billing_group=BillingGroupEdm(id="1223", prefer_way=PaymentType.prepaid))


factAccountEdm = AccountEdm.get_account()
print(str(factAccountEdm))
result = map_to(factAccountEdm, FactAccountBillingBiller)
print(str(result))
print(result.model_dump_json())

````

I don't know how to map the way as you suggest for `BillingGroupBiller`

**Comment by jakobkogler** [comment] 2023-09-13 16:04
And since I run/fixed the code locally, here's the working example:

<details>

```python
from enum import Enum

from dataclass_mapper import mapper, mapper_from, map_to, init_with_default, enum_mapper
from pydantic import BaseModel, Field
from typing import Optional


class AccountStateBiller(str, Enum):
    """
    The account states
    """
    ACTIVE = "0"
    CLOSED = "1"


type_mapping = {
    "prepaid": "PRE_PAID",
    "postpaid": "POST_PAID"
}

class PaymentTypeBiller(str, Enum):
    POST_PAID = "POST_PAID"
    PRE_PAID = "PRE_PAID"

@enum_mapper(PaymentTypeBiller, type_mapping)
class PaymentType(str, Enum):
    prepaid = "Prepaid"
    postpaid = "Postpaid"


account_billing_edm_to_biller = {
    "id": init_with_default(),
    "status_id": init_with_default()
}


class AccountBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    status_id: Optional[AccountStateBiller] = Field(default=None)


@mapper(AccountBiller, account_billing_edm_to_biller)
class AccountBillingEdm(BaseModel):
    id: str = Field(..., description="The account unique identifier")


@mapper(AccountBillingEdm)
@mapper_from(AccountBillingEdm)
class AccountBillingSfcc(BaseModel):
    id: str = Field(..., description="The account unique identifier")


# BillingGroupEdm -> BillingGroupBiller
billing_group_edm_to_billing_group_biller = {
    "id": init_with_default(),
}

fact_account_billing_edm_to_biller = {
    "account": "account_billing"
}


class BillingGroupBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    billing_group_type: PaymentTypeBiller = Field(...)


class FactAccountBillingBiller(BaseModel):
    account: AccountBiller = Field(...)
    billing_group: Optional[BillingGroupBiller] = Field(default=None,
                                                        description="Attributes relevant to a billing group needed to "
                                                                    "be stored in CD Rator")


@mapper(BillingGroupBiller, billing_group_edm_to_billing_group_biller)
class BillingGroupEdm(BaseModel):
    id: Optional[str] = Field(default=None)
    billing_group_type: PaymentType = Field(...)


@mapper(FactAccountBillingBiller, fact_account_billing_edm_to_biller)
class AccountEdm(BaseModel):
    account_billing: AccountBillingEdm = Field(...)
    billing_group: Optional[BillingGroupEdm] = Field(default=None)

    @staticmethod
    def get_account() -> 'AccountEdm':
        return AccountEdm(account_billing=map_to(AccountBillingSfcc(id="1234"), AccountBillingEdm),
                          billing_group=BillingGroupEdm(id="1223", billing_group_type=PaymentType.prepaid))


factAccountEdm = AccountEdm.get_account()
print(repr(factAccountEdm))
result = map_to(factAccountEdm, FactAccountBillingBiller)
print(repr(result))
print(result.model_dump_json())
```
</details>

**Comment by zhengye1** [comment] 2023-09-13 16:45
I think last issue I have.. for `billing_group_edm_to_billing_group_biller` it have one more field call "owner_id", which was using `owner` in `AccountEdm` class, and definition is `FactAccountBillingBiller` will have `owner` field.. 

the old mapping way is 
```
billing_group_edm_to_billing_group_biller = lambda self: None if self.billing_group is None else {
    "id": IGNORE_MISSING_MAPPING,
    "billing_group_type": PaymentTypeBiller.POST_PAID if self.billing_group.billing_group_type == PaymentType.postpaid else PaymentTypeBiller.PRE_PAID,
    "owner_id": self.owner
}
```

What should I fix?

**Comment by jakobkogler** [comment] 2023-09-13 17:47
Just add a mapping `"owner": "owner_id"` to the `AccountEdm` -> `FactAccountBillingBiller` mapping.
That's the first feature in the documentation: [Mapping by field names](https://dataclass-mapper.readthedocs.io/en/latest/features.html#mapping-by-field-names)

**Comment by zhengye1** [comment] 2023-09-13 18:08
oh sorry... I am looking at the wrong class.. also have the `owner_id` field in `BillingGroupBiller`
Maybe it is easier to put the full code..
```
from enum import Enum
from typing import List

from dataclass_mapper import mapper, mapper_from, map_to, IGNORE_MISSING_MAPPING, init_with_default, enum_mapper
from pydantic import BaseModel, Field
from typing import Optional

type_mapping = {
    "prepaid": "PRE_PAID",
    "postpaid": "POST_PAID"
}


class AccountStateBiller(str, Enum):
    """
    The account states
    """
    ACTIVE = "0"
    CLOSED = "1"


class PaymentTypeBiller(str, Enum):
    POST_PAID = "POST_PAID"
    PRE_PAID = "PRE_PAID"


@enum_mapper(PaymentTypeBiller, type_mapping)
class PaymentType(str, Enum):
    prepaid = "Prepaid"
    postpaid = "Postpaid"


account_billing_edm_to_biller = {
    "id": IGNORE_MISSING_MAPPING,
    "status_id": IGNORE_MISSING_MAPPING
}


class AccountBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    status_id: Optional[AccountStateBiller] = Field(default=None)


@mapper(AccountBiller, account_billing_edm_to_biller)
class AccountBillingEdm(BaseModel):
    id: str = Field(..., description="The account unique identifier")


@mapper(AccountBillingEdm)
@mapper_from(AccountBillingEdm)
class AccountBillingSfcc(BaseModel):
    id: str = Field(..., description="The account unique identifier")


# BillingGroupEdm -> BillingGroupBiller
billing_group_edm_to_billing_group_biller = lambda self: None if self.billing_group is None else {
    "id": IGNORE_MISSING_MAPPING,
    "billing_group_type": PaymentTypeBiller.POST_PAID if self.billing_group.billing_group_type == PaymentType.postpaid else PaymentTypeBiller.PRE_PAID,
    "owner_id": self.owner
}

fact_account_billing_edm_to_biller = {
    "account": "account_billing",
    "billing_group": billing_group_edm_to_billing_group_biller,
    "owner": "owner"
}


class BillingGroupBiller(BaseModel):
    id: Optional[str] = Field(default=None)
    billing_group_type: PaymentTypeBiller = Field(...)
    owner_id: str = Field(...)


class FactAccountBillingBiller(BaseModel):
    account: AccountBiller = Field(...)
    billing_group: Optional[BillingGroupBiller] = Field(default=None,
                                                        description="Attributes relevant to a billing group needed to "
                                                                    "be stored in CD Rator")
    owner: str = Field(default=None)


class BillingGroupEdm(BaseModel):
    id: Optional[str] = Field(default=None)
    billing_group_type: PaymentType = Field(...)


@mapper(FactAccountBillingBiller, fact_account_billing_edm_to_biller)
class AccountEdm(BaseModel):
    account_billing: AccountBillingEdm = Field(...)
    billing_group: Optional[BillingGroupEdm] = Field(default=None)
    owner: str = Field(default=None)

    @staticmethod
    def get_account() -> 'AccountEdm':
        return AccountEdm(account_billing=map_to(AccountBillingSfcc(id="1234"), AccountBillingEdm),
                          billing_group=BillingGroupEdm(id="1223", prefer_way=PaymentType.prepaid),
                          owner="123id")


factAccountEdm = AccountEdm.get_account()
print(str(factAccountEdm))
result = map_to(factAccountEdm, FactAccountBillingBiller)
print(str(result))
print(result.model_dump_json())
```

**Comment by jakobkogler** [comment] 2023-09-13 18:26
Ok, so you want to bring a variable from the parent source class `AccountEdm` into the child target class `BillingGroupBiller`.
There is currently not a really nice way of doing this. It's not possible to combine two classes into one.

The only way to accomplish this as the moment, is to provide die value for the `owner_id` via an extra context: https://dataclass-mapper.readthedocs.io/en/latest/features.html#provide-extra-context-to-mapping

So something like the following:

```python
billing_group_edm_to_billing_group_biller = {
    "id": IGNORE_MISSING_MAPPING,
    "billing_group_type": PaymentTypeBiller.POST_PAID if self.billing_group.billing_group_type == PaymentType.postpaid else PaymentTypeBiller.PRE_PAID,
    "owner_id": provide_with_extra()  # <- you mark the element with this marker
}
```

And when you map you need to specify the extra with the full path.

```python
map_to(factAccountEdm, FactAccountBillingBiller, extra={"billing_group": {"owner_id": factAccountEdm.owner}})
```

**Closed** 2023-09-16 06:40 UTC
